# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-09 01:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('briefcase', '0002_auto_20170508_0316'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='cat_col1',
            field=models.CharField(default='#989898', max_length=127),
        ),
        migrations.AddField(
            model_name='entry',
            name='cat_col2',
            field=models.CharField(default='#ffffff', max_length=127),
        ),
    ]
